version: '3.8'

services:
  appium:
    build: ./docker
    container_name: appium
    ports:
      - "4723:4723"
    volumes:
      - ./apps:/apps
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4723/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 10