version: "3.8"
services:
  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  appium:
    build:
      context: ./docker/appium
    container_name: appium
    volumes:
      - ./apps:/apps
    ports:
      - "4723:4723"
    depends_on:
      - selenium-hub

  node:
    image: selenium/node-docker:4.21.0
    container_name: node
    depends_on:
      - appium
      - selenium-hub
    volumes:
      - ./docker/node1.toml:/opt/selenium/config.toml
    command: >
      java -jar /opt/selenium/selenium-server.jar node --config /opt/selenium/config.toml