version: "3.8"
services:
  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  appium:
    image: appium/appium:latest
    container_name: appium
    volumes:
      - ./apps:/apps
      - ./docker/appium1.yml:/config/appium1.yml
      - ./docker/entrypoint.sh:/entrypoint.sh
    ports:
      - "4723:4723"
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    privileged: true

  node:
    image: selenium/node-docker:4.21.0
    container_name: node
    depends_on:
      - selenium-hub
      - appium
    volumes:
      - ./docker/node1.toml:/opt/selenium/config.toml
    command: >
      java -jar /opt/selenium/selenium-server.jar node --config /opt/selenium/config.toml