version: '3.8'

services:
  appium:
    image: budtmo/docker-android-x86-11.0:latest
    container_name: appium
    privileged: true
    ports:
      - "4723:4723"
      - "5554:5554"
      - "5555:5555"
    volumes:
      - ./apps:/apps
    environment:
      - CONNECT_TIMEOUT=600
      - ADB_INSTALL_TIMEOUT=600
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4723/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 10