version: '3.8'

services:
  android_emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: android_emulator
    privileged: true
    ports:
      - "4723:4723"  # Appium
      - "6080:6080"  # noVNC
      - "5554:5554"  # Emulator console
      - "5555:5555"  # ADB
    environment:
      - DEVICE=Samsung Galaxy S10
      - APPIUM=true
      - AUTO_RECORD=false
      - APPIUM_ARGS=--base-path=/wd/hu
      - VERBOSE=true
    volumes:
      - ./apps:/apps
    healthcheck:
      test: curl --fail http://localhost:4723/wd/hub/status || exit 1
      interval: 15s
      timeout: 10s
      retries: 10