version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  android_emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: android_emulator
    privileged: true
    depends_on:
      - selenium-hub
    ports:
      - "4723:4723"  # Appium
      - "6080:6080"  # noVNC
      - "5554:5554"  # Emulator console
      - "5555:5555"  # ADB
    environment:
      - DEVICE=Samsung Galaxy S10
      - APPIUM=true
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium-hub
      - SELENIUM_PORT=4444
    volumes:
      - ./apps:/apps
    healthcheck:
      test: curl --fail http://localhost:4723/wd/hub/status || exit 1
      interval: 15s
      timeout: 10s
      retries: 10