[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://appium:4723/wd/hub"
status-endpoint = "/status"
configs = [
  "1", "{\"platformName\": \"Android\", \"appium:platformVersion\": \"11.0\", \"appium:deviceName\": \"Android Emulator\", \"appium:automationName\": \"UiAutomator2\"}"
]

[sessionqueue]
session-request-timeout = 300
session-retry-interval = 5