[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://appium1:4723"
status-endpoint = "/status"
configs = [
  "1", "{\"platformName\": \"Android\", \"appium:platformVersion\": \"11.0\", \"appium:deviceName\": \"Android Emulator\", \"appium:automationName\": \"UiAutomator2\"}"
]
